apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: devops-toolkit
  namespace: clusters
spec:
  repo: https://github.com/sujith-es/rancher-fleet-demo
  branch: main
  targetNamespace: default
  paths:
  - helm
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
  - name: staging
    clusterSelector:
      matchLabels:
        env: staging
  - name: production
    clusterGroup: production
