apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: devops-toolkit
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  repo: https://github.com/sujith-es/rancher-fleet-demo
  branch: main
  targetNamespace: production
  paths:
  # - kustomize/overlays/production
    - kustomize/base

