apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: devops-toolkit
  namespace: fleet-local
spec:
  repo: https://github.com/sujith-es/rancher-fleet-demo
  branch: main
  targetNamespace: production
  paths:
  - helm
